# This file was generated by GoReleaser. DO NOT EDIT.
cask "adf-cli" do
  module GitHubHelper
    def self.token
      require "utils/github"

      github_token = ENV["HOMEBREW_GITHUB_API_TOKEN"]
      github_token ||= GitHub::API.credentials
      raise "Failed to retrieve github api token" if github_token.nil? || github_token.empty?

      github_token
    end

    def self.release_asset_url(tag, name)
      require "json"
      require "net/http"
      require "uri"

      resp = Net::HTTP.get(
        URI.parse("https://api.github.com/repos/jetrails/adf-cli/releases/tags/#{tag}"),
        {
          "Accept" => "application/vnd.github+json",
          "Authorization" => "Bearer #{token}",
          "X-GitHub-Api-Version" => "2022-11-28"
        }
      )

      release = JSON.parse(resp)
      release["assets"].find { |asset| asset["name"] == name }["url"]
    end
  end

  version "0.0.6"

  on_macos do
    on_intel do
      sha256 "e25834d469a58c77af8771b0b85c88ae6ff15175eb1bc25cfbf5298f27a0f93e"
      url "#{GitHubHelper.release_asset_url("#{version}", "adf-cli_#{version}_darwin_amd64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubHelper.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
    end
    on_arm do
      sha256 "b3ef7c6cdc725c64657ac4fded67ea61141cf7fa433b7c1ce144dcc07b46b6f0"
      url "#{GitHubHelper.release_asset_url("#{version}", "adf-cli_#{version}_darwin_arm64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubHelper.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
    end
  end

  on_linux do
    on_intel do
      sha256 "42cfed3b1c1d93395534f51d4e28c58ba85d933791d6352189a927c96cb24550"
      url "#{GitHubHelper.release_asset_url("#{version}", "adf-cli_#{version}_linux_amd64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubHelper.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
    end
    on_arm do
      sha256 "672a9ff0e62a87353038954e74ea669ed6f390feb17da55fb9cf2f5c8bc2e232"
      url "#{GitHubHelper.release_asset_url("#{version}", "adf-cli_#{version}_linux_arm64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubHelper.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
    end
  end

  name "adf-cli"
  desc "ADF Command-Line Tool"
  homepage "https://github.com/jetrails/adf-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "adf"
  bash_completion "./completions/adf.bash"
  fish_completion "./completions/adf.fish"
  zsh_completion "./completions/_adf"

  # No zap stanza required

end
