# This file was generated by GoReleaser. DO NOT EDIT.
cask "adf-cli" do
  module GitHubHelper
    def self.token
      require "utils/github"

      github_token = ENV["HOMEBREW_GITHUB_API_TOKEN"]
      github_token ||= GitHub::API.credentials
      raise "Failed to retrieve github api token" if github_token.nil? || github_token.empty?

      github_token
    end

    def self.release_asset_url(tag, name)
      require "json"
      require "net/http"
      require "uri"

      resp = Net::HTTP.get(
        URI.parse("https://api.github.com/repos/jetrails/adf-cli/releases/tags/#{tag}"),
        {
          "Accept" => "application/vnd.github+json",
          "Authorization" => "Bearer #{token}",
          "X-GitHub-Api-Version" => "2022-11-28"
        }
      )

      release = JSON.parse(resp)
      release["assets"].find { |asset| asset["name"] == name }["url"]
    end
  end

  version "0.0.11"

  on_macos do
    on_intel do
      sha256 "b44f85340d2979fa4b470c542751f3e13e1a694d994a4141530e71ea853798e0"
      url "#{GitHubHelper.release_asset_url("#{version}", "adf-cli_#{version}_darwin_amd64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubHelper.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
    end
    on_arm do
      sha256 "5534de70926f90fb473e8400e5b19af7e6f4aab99cff6976be930ef0d4ee1868"
      url "#{GitHubHelper.release_asset_url("#{version}", "adf-cli_#{version}_darwin_arm64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubHelper.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
    end
  end

  on_linux do
    on_intel do
      sha256 "1fdd66b371a2bab13b36a1b533aa07a7604c1d2864ecfbaedcb7f6a8cf902ba7"
      url "#{GitHubHelper.release_asset_url("#{version}", "adf-cli_#{version}_linux_amd64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubHelper.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
    end
    on_arm do
      sha256 "e7d9b36102ac888d14ca85f075e9d6eb5535fde55975c9ba69ea763f78c785ce"
      url "#{GitHubHelper.release_asset_url("#{version}", "adf-cli_#{version}_linux_arm64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubHelper.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
    end
  end

  name "adf-cli"
  desc "ADF Command-Line Tool"
  homepage "https://github.com/jetrails/adf-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "adf"
  bash_completion "./completions/adf.bash"
  fish_completion "./completions/adf.fish"
  zsh_completion "./completions/_adf"

  # No zap stanza required

end
