# This file was generated by GoReleaser. DO NOT EDIT.
cask "adf-cli" do
  module GitHubHelper
    def self.token
      require "utils/github"

      github_token = ENV["HOMEBREW_GITHUB_API_TOKEN"]
      github_token ||= GitHub::API.credentials
      raise "Failed to retrieve github api token" if github_token.nil? || github_token.empty?

      github_token
    end

    def self.release_asset_url(tag, name)
      require "json"
      require "net/http"
      require "uri"

      resp = Net::HTTP.get(
        URI.parse("https://api.github.com/repos/jetrails/adf-cli/releases/tags/#{tag}"),
        {
          "Accept" => "application/vnd.github+json",
          "Authorization" => "Bearer #{token}",
          "X-GitHub-Api-Version" => "2022-11-28"
        }
      )

      release = JSON.parse(resp)
      release["assets"].find { |asset| asset["name"] == name }["url"]
    end
  end

  version "0.0.12"

  on_macos do
    on_intel do
      sha256 "3e7af19ffb7e13f2f85308aa80613ec838b78e5caefa41fdf4d6237d068bf397"
      url "#{GitHubHelper.release_asset_url("#{version}", "adf-cli_#{version}_darwin_amd64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubHelper.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
    end
    on_arm do
      sha256 "5b754be0b9cd68534e0371ebc6e2a400ec137d1adf37916fb47d141eaebe76a5"
      url "#{GitHubHelper.release_asset_url("#{version}", "adf-cli_#{version}_darwin_arm64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubHelper.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
    end
  end

  on_linux do
    on_intel do
      sha256 "3e2a4cfacb41377eb69412cbc6f67bdfeada23944fe9a11bd84a185caddcc6a2"
      url "#{GitHubHelper.release_asset_url("#{version}", "adf-cli_#{version}_linux_amd64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubHelper.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
    end
    on_arm do
      sha256 "05b6879426a134504a89eb279967f61f87672d859c8ef2ed2447102ce227fa9b"
      url "#{GitHubHelper.release_asset_url("#{version}", "adf-cli_#{version}_linux_arm64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubHelper.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
    end
  end

  name "adf-cli"
  desc "ADF Command-Line Tool"
  homepage "https://github.com/jetrails/adf-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "adf"
  bash_completion "./completions/adf.bash"
  fish_completion "./completions/adf.fish"
  zsh_completion "./completions/_adf"

  # No zap stanza required

end
