# This file was generated by GoReleaser. DO NOT EDIT.
cask "jrcft" do
  module GitHubHelper
    def self.token
      require "utils/github"

      github_token = ENV["HOMEBREW_GITHUB_API_TOKEN"]
      github_token ||= GitHub::API.credentials
      raise "Failed to retrieve github api token" if github_token.nil? || github_token.empty?

      github_token
    end

    def self.release_asset_url(tag, name)
      require "json"
      require "net/http"
      require "uri"

      resp = Net::HTTP.get(
        URI.parse("https://api.github.com/repos/jetrails/jrcft/releases/tags/#{tag}"),
        {
          "Accept" => "application/vnd.github+json",
          "Authorization" => "Bearer #{token}",
          "X-GitHub-Api-Version" => "2022-11-28"
        }
      )

      release = JSON.parse(resp)
      release["assets"].find { |asset| asset["name"] == name }["url"]
    end
  end

  version "0.0.2"

  on_macos do
    on_intel do
      sha256 "e1e5214ee3441293feeb0a24fad27e0e18a2ceee44d23d0169916c085925f366"
      url "#{GitHubHelper.release_asset_url("#{version}", "jrcft_#{version}_darwin_amd64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubHelper.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
    end
    on_arm do
      sha256 "9abec878b138a49831d38c189db8cc431aa822364767f91f64e232d399cdf3e3"
      url "#{GitHubHelper.release_asset_url("#{version}", "jrcft_#{version}_darwin_arm64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubHelper.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
    end
  end

  on_linux do
    on_intel do
      sha256 "44580d180733ee9b591aef31a0785d02e0bd669b71f4338feaef3c089832fed7"
      url "#{GitHubHelper.release_asset_url("#{version}", "jrcft_#{version}_linux_amd64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubHelper.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
    end
    on_arm do
      sha256 "9c0c12b26ff49083e45c765360db2925bc8d0e0ae6b8e52c39b7f80be75886b5"
      url "#{GitHubHelper.release_asset_url("#{version}", "jrcft_#{version}_linux_arm64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubHelper.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
    end
  end

  name "jrcft"
  desc "JetRails CloudFormation Template Tool"
  homepage "https://github.com/jetrails/jrcft"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jrcft"
  bash_completion "./completions/jrcft.bash"
  fish_completion "./completions/jrcft.fish"
  zsh_completion "./completions/_jrcft"

  # No zap stanza required

end
