# This file was generated by GoReleaser. DO NOT EDIT.
cask "jrcft" do
  module GitHubHelper
    def self.token
      require "utils/github"

      github_token = ENV["HOMEBREW_GITHUB_API_TOKEN"]
      github_token ||= GitHub::API.credentials
      raise "Failed to retrieve github api token" if github_token.nil? || github_token.empty?

      github_token
    end

    def self.release_asset_url(tag, name)
      require "json"
      require "net/http"
      require "uri"

      resp = Net::HTTP.get(
        URI.parse("https://api.github.com/repos/jetrails/jrcft/releases/tags/#{tag}"),
        {
          "Accept" => "application/vnd.github+json",
          "Authorization" => "Bearer #{token}",
          "X-GitHub-Api-Version" => "2022-11-28"
        }
      )

      release = JSON.parse(resp)
      release["assets"].find { |asset| asset["name"] == name }["url"]
    end
  end

  version "0.0.1"

  on_macos do
    on_intel do
      sha256 "87dca76288e49a8fce63c7f0429fef8b43d375e4396cba147d154248162e6630"
      url "#{GitHubHelper.release_asset_url("#{version}", "jrcft_#{version}_darwin_amd64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubHelper.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
    end
    on_arm do
      sha256 "a00c0ed74892c8955e8c22cf235db3fe55f0adde5f48bb1b3b470cc2c7e83546"
      url "#{GitHubHelper.release_asset_url("#{version}", "jrcft_#{version}_darwin_arm64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubHelper.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
    end
  end

  on_linux do
    on_intel do
      sha256 "c1437600f7a2f4d7a2b2678c1a16d4f0dbc3c9b914c3fa255a73872703230659"
      url "#{GitHubHelper.release_asset_url("#{version}", "jrcft_#{version}_linux_amd64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubHelper.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
    end
    on_arm do
      sha256 "fb8af5dfcda0ce5769c34f6a4f7b6d6f360780bd329540c638430637d108b007"
      url "#{GitHubHelper.release_asset_url("#{version}", "jrcft_#{version}_linux_arm64.tar.gz")}",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{GitHubHelper.token}",
          "X-GitHub-Api-Version: 2022-11-28",
        ]
    end
  end

  name "jrcft"
  desc "JetRails CloudFormation Template Tool"
  homepage "https://github.com/jetrails/jrcft"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jrcft"
  bash_completion "./completions/jrcft.bash"
  fish_completion "./completions/jrcft.fish"
  zsh_completion "./completions/_jrcft"

  # No zap stanza required

end
