class Jrctl < Formula

	desc "Command line tool to help interact with our API"
	homepage "https://github.com/jetrails/jrctl"
	url "https://github.com/jetrails/jrctl/releases/download/3.2.0/jrctl_3.2.0_darwin_amd64.tar.gz"
	sha256 "a4eae9872bb316458938da2df4485a36e0e0a4b9d1f9358721c14f514f24ab5f"
	version "3.2.0"

	def install
		bin.install "bin/jrctl_darwin_amd64" => "jrctl"
		man1.install "man/jrctl-database-create.1"
		man1.install "man/jrctl-database-delete.1"
		man1.install "man/jrctl-database-link.1"
		man1.install "man/jrctl-database-list.1"
		man1.install "man/jrctl-database-unlink.1"
		man1.install "man/jrctl-database-user-create.1"
		man1.install "man/jrctl-database-user-delete.1"
		man1.install "man/jrctl-database-user-list.1"
		man1.install "man/jrctl-database-user-password.1"
		man1.install "man/jrctl-database-user.1"
		man1.install "man/jrctl-database.1"
		man1.install "man/jrctl-firewall-allow-cloudflare.1"
		man1.install "man/jrctl-firewall-allow.1"
		man1.install "man/jrctl-firewall-deny.1"
		man1.install "man/jrctl-firewall-list.1"
		man1.install "man/jrctl-firewall-unallow-cloudflare.1"
		man1.install "man/jrctl-firewall-unallow.1"
		man1.install "man/jrctl-firewall-undeny.1"
		man1.install "man/jrctl-firewall.1"
		man1.install "man/jrctl-report-audit.1"
		man1.install "man/jrctl-report.1"
		man1.install "man/jrctl-secret-create.1"
		man1.install "man/jrctl-secret-delete.1"
		man1.install "man/jrctl-secret-read.1"
		man1.install "man/jrctl-secret.1"
		man1.install "man/jrctl-server-ingest.1"
		man1.install "man/jrctl-server-list.1"
		man1.install "man/jrctl-server-version.1"
		man1.install "man/jrctl-server.1"
		man1.install "man/jrctl-service-disable.1"
		man1.install "man/jrctl-service-enable.1"
		man1.install "man/jrctl-service-list.1"
		man1.install "man/jrctl-service-reload.1"
		man1.install "man/jrctl-service-restart.1"
		man1.install "man/jrctl-service.1"
		man1.install "man/jrctl-update.1"
		man1.install "man/jrctl-utility-mkpass.1"
		man1.install "man/jrctl-utility.1"
		man1.install "man/jrctl-version.1"
		man1.install "man/jrctl-website-list.1"
		man1.install "man/jrctl-website-php-available.1"
		man1.install "man/jrctl-website-php-switch.1"
		man1.install "man/jrctl-website.1"
		man1.install "man/jrctl.1"
		system "#{bin}/jrctl completion bash > /usr/local/etc/bash_completion.d/jrctl"
	end

	test do
		system "#{bin}/jrctl", "version"
	end

end
