class Jrctl < Formula

	desc "Command line tool to help interact with our API"
	homepage "https://github.com/jetrails/jrctl"
	version "4.0.1"







	on_macos do
		if Hardware::CPU.intel?
			url "https://github.com/jetrails/jrctl/releases/download/4.0.1/jrctl_4.0.1_darwin_amd64.tar.gz"
			sha256 "67391e2e76816312da522d36781ae6dd3c380cd1379722286d51464627dcf9a4"
			def install
				bin.install "bin/jrctl_darwin_amd64" => "jrctl"
				man1.install "man/jrctl-alternative-list.1"
				man1.install "man/jrctl-alternative-switch.1"
				man1.install "man/jrctl-alternative.1"
				man1.install "man/jrctl-database-create.1"
				man1.install "man/jrctl-database-delete.1"
				man1.install "man/jrctl-database-link.1"
				man1.install "man/jrctl-database-list.1"
				man1.install "man/jrctl-database-unlink.1"
				man1.install "man/jrctl-database-user-create.1"
				man1.install "man/jrctl-database-user-delete.1"
				man1.install "man/jrctl-database-user-list.1"
				man1.install "man/jrctl-database-user-password.1"
				man1.install "man/jrctl-database-user.1"
				man1.install "man/jrctl-database.1"
				man1.install "man/jrctl-firewall-allow-cloudflare.1"
				man1.install "man/jrctl-firewall-allow.1"
				man1.install "man/jrctl-firewall-deny.1"
				man1.install "man/jrctl-firewall-list.1"
				man1.install "man/jrctl-firewall-unallow-cloudflare.1"
				man1.install "man/jrctl-firewall-unallow.1"
				man1.install "man/jrctl-firewall-undeny.1"
				man1.install "man/jrctl-firewall.1"
				man1.install "man/jrctl-node-delete.1"
				man1.install "man/jrctl-node-ingest.1"
				man1.install "man/jrctl-node-list.1"
				man1.install "man/jrctl-node-version.1"
				man1.install "man/jrctl-node.1"
				man1.install "man/jrctl-report-audit.1"
				man1.install "man/jrctl-report.1"
				man1.install "man/jrctl-secret-create.1"
				man1.install "man/jrctl-secret-delete.1"
				man1.install "man/jrctl-secret-read.1"
				man1.install "man/jrctl-secret.1"
				man1.install "man/jrctl-service-disable.1"
				man1.install "man/jrctl-service-enable.1"
				man1.install "man/jrctl-service-list.1"
				man1.install "man/jrctl-service-reload.1"
				man1.install "man/jrctl-service-restart.1"
				man1.install "man/jrctl-service.1"
				man1.install "man/jrctl-utility-mkpass.1"
				man1.install "man/jrctl-utility.1"
				man1.install "man/jrctl-version-update.1"
				man1.install "man/jrctl-version.1"
				man1.install "man/jrctl-website-list.1"
				man1.install "man/jrctl-website-php-available.1"
				man1.install "man/jrctl-website-php-switch.1"
				man1.install "man/jrctl-website.1"
				man1.install "man/jrctl.1"
				# system "#{bin}/jrctl completion bash > /usr/local/etc/bash_completion.d/jrctl"
			end
		end
		if Hardware::CPU.arm?
			url "https://github.com/jetrails/jrctl/releases/download/4.0.1/jrctl_4.0.1_darwin_arm64.tar.gz"
			sha256 "56c34baf90d5445fb5b47d9bef8a6d44214a5ec53e768bf9e043136da1a249da"
			def install
				bin.install "bin/jrctl_darwin_arm64" => "jrctl"
				man1.install "man/jrctl-alternative-list.1"
				man1.install "man/jrctl-alternative-switch.1"
				man1.install "man/jrctl-alternative.1"
				man1.install "man/jrctl-database-create.1"
				man1.install "man/jrctl-database-delete.1"
				man1.install "man/jrctl-database-link.1"
				man1.install "man/jrctl-database-list.1"
				man1.install "man/jrctl-database-unlink.1"
				man1.install "man/jrctl-database-user-create.1"
				man1.install "man/jrctl-database-user-delete.1"
				man1.install "man/jrctl-database-user-list.1"
				man1.install "man/jrctl-database-user-password.1"
				man1.install "man/jrctl-database-user.1"
				man1.install "man/jrctl-database.1"
				man1.install "man/jrctl-firewall-allow-cloudflare.1"
				man1.install "man/jrctl-firewall-allow.1"
				man1.install "man/jrctl-firewall-deny.1"
				man1.install "man/jrctl-firewall-list.1"
				man1.install "man/jrctl-firewall-unallow-cloudflare.1"
				man1.install "man/jrctl-firewall-unallow.1"
				man1.install "man/jrctl-firewall-undeny.1"
				man1.install "man/jrctl-firewall.1"
				man1.install "man/jrctl-node-delete.1"
				man1.install "man/jrctl-node-ingest.1"
				man1.install "man/jrctl-node-list.1"
				man1.install "man/jrctl-node-version.1"
				man1.install "man/jrctl-node.1"
				man1.install "man/jrctl-report-audit.1"
				man1.install "man/jrctl-report.1"
				man1.install "man/jrctl-secret-create.1"
				man1.install "man/jrctl-secret-delete.1"
				man1.install "man/jrctl-secret-read.1"
				man1.install "man/jrctl-secret.1"
				man1.install "man/jrctl-service-disable.1"
				man1.install "man/jrctl-service-enable.1"
				man1.install "man/jrctl-service-list.1"
				man1.install "man/jrctl-service-reload.1"
				man1.install "man/jrctl-service-restart.1"
				man1.install "man/jrctl-service.1"
				man1.install "man/jrctl-utility-mkpass.1"
				man1.install "man/jrctl-utility.1"
				man1.install "man/jrctl-version-update.1"
				man1.install "man/jrctl-version.1"
				man1.install "man/jrctl-website-list.1"
				man1.install "man/jrctl-website-php-available.1"
				man1.install "man/jrctl-website-php-switch.1"
				man1.install "man/jrctl-website.1"
				man1.install "man/jrctl.1"
				# system "#{bin}/jrctl completion bash > /usr/local/etc/bash_completion.d/jrctl"
			end
		end
	end

	test do
		system "#{bin}/jrctl", "version"
	end

end
